//UX3 imports
import '../../../../plugins/jquery/jquery.js'
import '../../../../plugins/jquery/jquery-migrate.js'
import '../../../../plugins/enquireJs/js/enquire.js'
import '../../../../plugins/scrollo/js/scrollo.js'
import '../../../../plugins/sticko/js/sticko.js'
import '../../../../plugins/auto-hide-bar/js/auto-hide-bar.js'
import "../../../../plugins/owl-carousel/js/owl.carousel.min.js";
import '../../../../plugins/modal/js/modal.js'

/*JCF plugin*/
import '../../../../plugins/custom-form/js/jcf.js'
import '../../../../plugins/custom-form/js/jcf.select.js'
import '../../../../plugins/custom-form/js/jcf.file.js'
import '../../../../plugins/custom-form/js/jcf.button.js'
import '../../../../plugins/custom-form/js/jcf.checkbox.js'
import '../../../../plugins/custom-form/js/jcf.number.js'
import '../../../../plugins/custom-form/js/jcf.radio.js'
import '../../../../plugins/custom-form/js/jcf.range.js'
import '../../../../plugins/custom-form/js/jcf.scrollable.js'
import '../../../../plugins/custom-form/js/jcf.textarea.js'
import '../../../../plugins/custom-form/js/jcf.start.js'
import '../../../../plugins/panzoom/jquery.panzoom.js'
import '../../../../plugins/touchSwipe/jquery.touchSwipe.js'
import '../../../../plugins/controller/js/controller.js'
import '../../../../plugins/drawer/js/drawer.js'
import '../../../../plugins/lazyload/js/jquery.lazyload.js';
import '../../../../plugins/truncate/js/truncate.js';
import "../../../../plugins/magicSearch/js/magicsuggest.js";
import '../../../../plugins/transplant/js/transplant.js';
import '../../../../plugins/slide/js/slide.js';
import '../../../../plugins/tabs/js/tabs.js';
//ACM imports
import '../drawer/js/drawer.js'
import '../controller/js/controller.js'
import '../scrollo/js/scrollo.js'
import '../sticko/js/sticko.js'